version: '3'
services:
  walletApp:
    image: wallet
    build: .
    ports:
      - "7070:7070"
    restart: always
    depends_on:
      - walletDb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://walletDb/wallet
      - SPRING_DATASOURCE_USERNAME=newuser
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  walletDb:
    image: postgres:14.7
    restart: always
    ports:
      - "9999:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=newuser
      - POSTGRES_DB=wallet