spring.application.name=wallet

spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:postgresql://localhost:5432/wallet
#spring.datasource.username=newuser
#spring.datasource.password=12345

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wallet}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:newuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:/db/changelog/changeLog-master.xml
spring.liquibase.enabled=true

server.port=7070
logging.level.org.springframework.security=debug